language: python
python: 3.4
services:
  - mysql
env:
  - TOXENV=flake8
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
before_install:
  - pip install tox
before_script:
  # enable row-based binlog
  - sudo touch /etc/mysql/conf.d/replication.cnf
  - sudo chmod 777 /etc/mysql/conf.d/replication.cnf
  - echo '[mysqld]' > /etc/mysql/conf.d/replication.cnf
  - echo 'log-bin = mysql-bin' >> /etc/mysql/conf.d/replication.cnf
  - echo 'server-id = 1' >> /etc/mysql/conf.d/replication.cnf
  - echo 'binlog-format = row'  >> /etc/mysql/conf.d/replication.cnf
  - sudo chmod 700 /etc/mysql/conf.d/replication.cnf
  - sudo service mysql restart
script:
  - tox -v
